### PR TITLE
Add various links, replace SMLtoJs link

### PR DESCRIPTION
**Pull request by FrankRuben**
Great initiative - and hello Lassi :)

### CODE REVIEW

**Comment by lassik** [comment]
Hey Frank, great to see you around ML as well! Thanks for the extensive links. Please send more if you feel like it.

**Comment by FrankRuben** [comment]
> Hey Frank, great to see you around ML as well! Thanks for the extensive links. Please send more if you feel like it.

My third thought when "discovering" SML: if it would only have the one-man army Lassi as its proponent :).

I already copied over the most "official" links from my own link collection.

The next interesting pieces of information I would have liked to find when starting were some relevant attributes per implementation, such as: can build standalone executables, can compile to other runtime, has FFI, has REPL, support for compile-at-large, runs natively on Windows (advantage over OCaml for the time being), ....
This will be a lot of work to do exhaustively, but once the attributes are agreed upon, that information can be added piece by piece.

**Comment by lassik** [comment]
Wow, an honor! ... it does now! SML and Scheme programmers are starting to work together on important things.

SML has a website at http://smlfamily.org/ The kind of implementation information you list would ideally go on that site so that it becomes a central place for all things SML. I'll ask if they accept outside contributions to the site. Would you have some time work on it? I don't, but I'll always do my best to connect other people who share similar goals.

**Comment by FrankRuben** [comment]
> SML and Scheme programmers are starting to work together on important things.

Very interesting, that's a surprise. Both languages share many similarities; if there would be a reasonable way to bundle efforts it might help both to gain ground. As shown by the list of implementations here, there are some transpilers from ML to e.g. Lua or JS, so having Scheme as target should be in reach and with that the option to use its libraries and runtimes. Anyway your planned collaboration will have already better ideas :).

> SML has a website at http://smlfamily.org/ The kind of implementation information you list would ideally go on that site so that it becomes a central place for all things SML. I'll ask if they accept outside contributions to the site. Would you have some time work on it? I don't, but I'll always do my best to connect other people who share similar goals.

Time is always limited, but I can add least add the information I collected already and I keep collecting anyway - it just won't be available with one big content push. I'd be fine starting to add info here, then the experts can cross-check before it gets copied to the official Standard ML Family project.

**Pull request merged**
